### ISSUE TITLE
You just want to submit a PR for this in Teaspoon proper?

### ISSUE THREAD

**Issue by jejacks0n** [alejandrobabio/spring-commands-teaspoon#1]
Might be easier for me to maintain long term.. would only need a quick screenhero session or something so you can explain the few bits that I don't fully understand.

Thanks for the library, and if you don't want to include it in Teaspoon that's ok too.

**Comment by alejandrobabio** [comment]
Jeremy, I think we can join at 19 hs on Denver, 23 here (utc-3), today, tomorrow or any of these days. I don't have screenhero user, but you can invite me (screenhero has closed the signups). Or by Google Hangouts. Let me know if you can.

**Comment by alejandrobabio** [comment]
BTW, I think that spring-commands-teaspoon might not be part of Teaspoon. The same way that Rspec don't include spring-commands-rspec, the same as Cucumber. As a developer, you can chose if you want Spring or no from your Gemfile. On the other hand, Spring users know that they must add spring-commands for any not standard Rails tool that they use (like Rspec, Cucumber, or Teaspoon).

Some of the history of spring-commands here: https://github.com/rails/spring/issues/79 and https://github.com/rails/spring/issues/164.

I don't need to say that: but, this library is released under MIT Licence terms. You are free to copy and include it on Teaspoon. But I think the users of Spring doesn't expect that.

If you want to chat about this, or the internal of this library, of course, contact me and we'll do.
